### ISSUE TITLE
[Suggestion] Make this repo a "template"

### ISSUE THREAD

**Issue by AvinashReddy3108** [hrishikeshrt/flask-bootstrap-anywhere#1]
**Why?**
_So others can generate new repositories with the same directory structure, branches, and files as this repo._

**Some references :point_down:** 
- [Creating a template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)
- [Creating a repository from a template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template)

**Comment by hrishikeshrt** [comment]
Thank you for the suggestion!
Please check now.
